# Device section - fill in the data from your Watson IOT device
# all fields are required (publish)
device:
  id:
  organization:
  type:
  username: use-token-auth # has to be use token auth for devices
  token:

# This will result in the topic iot-2/evt/status/fmt/json
topic:
  format: json
  name: status

# Connection properties
connection:
  ssl: yes # automatically sets port to 8883 or 1883 respectively

# Consuming API settings (subscribe)
api:
  appId:  # Id of the app without a-organization-part (a-myorg-4rtfgtz -> 4rtfgtz)
  token:
  organization:
